# Generated by Django 5.1.2 on 2024-10-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=140)),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
